# Generated by Django 5.0.5 on 2024-05-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
