# Generated by Django 5.0.6 on 2024-05-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscriptionplan_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="months",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
