# Generated by Django 5.0.6 on 2024-05-13 04:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0004_subscriptionplan_months"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.FloatField()),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[(1, "SUCCESS"), (2, "FAILURE"), (3, "PENDING")],
                        default=3,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                (
                    "datetime_of_payment",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.JSONField(default=dict)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
