# Generated by Django 5.0.6 on 2024-05-22 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_movie_like_counts_comment_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviewishlist",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_users",
                to="main.movie",
            ),
        ),
    ]
